select (COUNT(DISTINCT ?v6) as ?cdv6) WHERE {
?v2 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country0> . 
?v0 <http://purl.org/goodrelations/offers> ?v2 . 
?v2 <http://purl.org/goodrelations/price> ?v3 . 
?v2 <http://purl.org/goodrelations/validFrom> ?v4 . 
?v2 <http://purl.org/goodrelations/validThrough> ?v5 . 
?v0 <http://schema.org/contactPoint> ?v8 . 
?v0 <http://purl.org/goodrelations/name> ?v1 . 
?v0 <http://schema.org/email> ?v10 . 
?v0 <http://schema.org/openingHours> ?v11 . 
?v6 <http://purl.org/stuff/rev#reviewer> ?v8 . 
?v6 <http://purl.org/stuff/rev#rating> ?v7 . 
}